name: RUN APP

on : [push]


jobs:
  build:
    name: run
    runs-on: ubuntu-latest

    steps:
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3

      - name: Say hi
        uses: actions/checkout@v1
        run: python app.py
