name: RUN APP

on : [push]


jobs:
  build:
    name: run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install python
        with:
          python-version: 3.8
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3

      - name: Say hi
        run: python app.py
